import re
import os

def translate():
    input_file = '/Users/honux/HobbyProjects/sf2/file/ja/2_original.html'
    output_file = '/Users/honux/HobbyProjects/sf2/file/en/2.html'

    with open(input_file, 'r', encoding='utf-8', errors='ignore') as f:
        content = f.read()

    # Translation map: (Korean, Japanese) -> (Korean, English)
    translations = [
        ('[항해]', '[Voyage]'),
        ('사라', 'Sarah'),
        ('으윽...배가...메쓱거려...우우우....', 'Ugh... the boat... I feel sick... ooooh....'),
        ('키위', 'Kiwi'),
        ('사라, 저길봐!', 'Look over there, Sarah!'),
        ('미안, 키위...지금은 아무것도 할수 없어....', 'Sorry, Kiwi... I can\'t do anything right now....'),
        ('그게 아니라...', 'It\'s not that...'),
        ('미안...우우욱...!', 'Sorry... uuuuugh...!'),
        ('야호, 육지다!', 'Yeah! Land!'),
        ('뭐? 정말이네! 아스트랄님, 육지가 보여요!', 'What? You\'re right! Sir Astral, I see land!'),
        ('아스트랄', 'Astral'),
        ('드디어 다다렀구나. 폐하, 파르메키아가 보이십니까?', 'We finally made it. Your Majesty, can you see Parmecia?'),
        ('그란실왕', 'King Granseal'),
        ('아, 잘됐네...', 'Ah, that\'s good...'),
        ('장관님, 파르메키아에 거의 다다렀습니다!', 'Minister, we have almost reached Parmecia!'),
        ('장관', 'Minister'),
        ('배를 상륙하시오, 선장.', 'Land the ship, Captain.'),
        ('선장', 'Captain'),
        ('어디로요?', 'Where to?'),
        ('아무곳이오. 거기요! 아니! 저기요!', 'Anywhere. There! No! Over there!'),
        ('하지만, 이 상태로 상륙하면 배는 부서지고말것입니다!', 'But if we land like this, the ship will be destroyed!'),
        ('상관없소이다. 이 배는 어차피 상륙후 목재로 쓰일것이오.', 'It doesn\'t matter. This ship will be used as lumber after we land anyway.'),
        ('진담이십니까? 나중에라도 배가없다고 불평하지 마쇼!', 'Are you serious? Don\'t complain later about not having a ship!'),
        ('슬래이드', 'Slade'),
        ('우와!', 'Whoa!'),
        ('배가 해변에 부딪혔어요! 아악!', 'The ship hit the beach! Aaah!'),
        ('웃챠! 웃챠! 이것이 바로 진정한 바다의 사나이라는것이지!', 'Heave-ho! Heave-ho! This is what it means to be a true man of the sea!'),
        ('그리하여 그란실의 사람들은 새로운 고향에 도착하였다.', 'And so, the people of Granseal arrived at their new home.'),
        ('모두들, 들으시오!', 'Everyone, listen!'),
        ('여기에 새로운 그란실을 지읍시다! 이 배는 좋은 목재가 될것이오! 배를 조각조각 뜯어서 목재를 육지로 나르시오!', 'Let\'s build a new Granseal here! This ship will provide good lumber! Take the ship apart piece by piece and carry the wood to land!'),
        ('쟈하', 'Jaha'),
        ('배를 조각조각 뜯어서 새로운 마을을 짓는대.... 그뜻은 우린 더이상 그란스섬으로 갈수없다는말이잖아! 야, 듣고있는거야?!', 'They\'re taking the ship apart to build a new town.... That means we can\'t go back to Grans Island anymore! Hey, are you listening?!'),
        ('조용해! 다들 알고있으니까. 이것좀 뜯어줘!', 'Quiet! Everyone knows that. Help me take this apart!'),
        ('알았어, 갈께.', 'Alright, I\'m coming.'),
        ('으윽...으으으윽...꽉 끼었는걸? 끙차! 끙차! 빠져라아아아아아!', 'Ugh... uuuugh... it\'s stuck tight! Heave! Ho! Come out!'),
        ('맙소사, 멍청하군!', 'Good grief, what an idiot!'),
        ('괜찮아. 쟈하는 어차피 목욕할때가 됐으니까.', 'It\'s okay. Jaha needed a bath anyway.'),
        ('카진', 'Kazin'),
        ('보우이, 이 나무조각을 갑판위로 올려다줘.', 'Bowie, carry this piece of wood up to the deck.'),
        ('나무조각에 다가갑시다.', 'Approach the piece of wood.'),
        ('나무조각을 들겠습니까?', 'Will you pick up the piece of wood?'),
        ('누구, 저 나무조각좀 들어줘!', 'Someone, please carry that piece of wood!'),
        ('젊은이', 'Young Man'),
        ('알았습니다!', 'Understood!'),
        ('고맙다, 꼬마야!', 'Thanks, kid!'),
        ('보우이는 나무조각을 건내준다.', 'Bowie hands over the piece of wood.'),
        ('새로운 마을을 위해 많은 목재가 필요하단다!', 'We need a lot of lumber for the new town!'),
        ('배가 없이는 그란실로 되돌아갈수가 없지... 물론 그란스섬엔 더이상 그란실이 없다는건 잘 알지만...하지만...', 'We can\'t go back to Granseal without a ship... Of course, I know Granseal is gone from Grans Island, but still...'),
        ('선원', 'Sailor'),
        ('누가좀 도와주세요!', 'Someone, please help!'),
        ('무슨일인가?', 'What\'s the matter?'),
        ('제 친구가 북쪽산길에서 아직 돌아오지 않았습니다. 분명 무슨 문제가 생긴것같습니다.', 'My friend hasn\'t returned from the north mountain path yet. Something must have happened.'),
        ('불길하군.', 'That sounds bad.'),
        ('보우이, 들었나? 북쪽산길로 가서 저녀석의 친구를 살펴보지 않겠나?', 'Bowie, did you hear that? Will you go to the north mountain path and look for his friend?'),
        ('아니오', 'No'),
        ('뭐라고? 안들린다. 다시 한번 말하겠다!', 'What? I didn\'t hear you. I\'ll say it again!'),
        ('예', 'Yes'),
        ('참으로 용감하구나! 야, 보우이가 같이 가겠단다!', 'How brave! Hey, Bowie is going!'),
        ('보우이, 고마워! 북쪽산길로 안내해줄게. 따라와.', 'Bowie, thanks! I\'ll lead you to the north mountain path. Follow me.'),
        ('보우이, 기다려. 기다려!', 'Bowie, wait. Wait!'),
        ('헤에, 다 젖었네?', 'Heh, you\'re all soaked?'),
        ('너 혼자만 떠나는길이야? 그럴수는 없지!', 'Are you leaving all by yourself? We can\'t let that happen!'),
        ('혼자 가기엔 너무 위험한것 같아.', 'It seems too dangerous to go alone.'),
        ('게다가...모두 같이 가면 더욱 안전하겠지. 가자고.', 'Besides... it\'ll be safer if we all go together. Let\'s go.'),
        ('[북쪽 산길]', '[North Mountain Path]'),
        ('저기있다! 저기에 있군!', 'There he is! He\'s over there!'),
        ('쓰러져있어! 왜지? 무슨일이야?', 'He\'s collapsed! Why? What happened?'),
        ('마녀', 'Witch'),
        ('히히! 더 많은 낯선사람들이 나타났구나!', 'Hee hee! More strangers have appeared!'),
        ('너! 네가 다치게 했나?', 'You! Did you hurt him?'),
        ('여기는 내 구역이야. 내가 보호하지. 저녀석을 구하러 왔다고? 웃기는군!', 'This is my territory. I protect it. You came to save him? Ridiculous!'),
        ('전원공격!', 'Attack, everyone!'),
        ('[전투 8]', '[Battle 8]'),
        ('보스 : 쓰러진 선원에 가장 가까운 헌터 고블린', 'Boss: Hunter Goblin closest to the fallen sailor'),
        ('유유히 상대하셔도 됩니다. 숲쪽의 길보다는 오른쪽으로 돌아서 가시는게 기동력도 살리고 편합니다. 역시 마녀들에게 키위를 보호합시다.', 'You can take your time. It\'s easier to go around to the right rather than through the forest path to maintain mobility. Make sure to protect Kiwi from the witches.'),
        ('[전투후]', '[After Battle]'),
        ('맙소사...야! 괜찮아?!', 'Good grief... Hey! Are you okay?!'),
        ('아!', 'Ah!'),
        ('선원의친구', 'Sailor\'s Friend'),
        ('우우우...으으으...큰 바위가...덮쳤어....', 'Uuuuu... uuuuugh... a large rock... hit me....'),
        ('응? 여기가 어디지?', 'Huh? Where am I?'),
        ('여기는...흐으음... ', 'This is... hmmm... '),
        ('보우이...네가 왜 여기 있는거야? ', 'Bowie... why are you here? '),
        ('이런 바보같으니. 우리는 널 구하러 왔다고! 우리가 안왔으면 지금쯤 넌 죽었을거야.', 'You idiot. We came to save you! You\'d be dead by now if we hadn\'t come.'),
        ('무슨 이야기를 하는거야? 아 맞아! 기억이 나는군. 네가 떠난후 아주 커다란 바위가 내게 떨어졌어. 그 바위때문에 난 기절했나봐. 어쨋거나 고마워. 저길봐! 산사태로 동굴입구가 막혔다.', 'What are you talking about? Oh, right! I remember now. After you left, a huge rock fell on me. I must have blacked out because of that rock. Anyway, thanks. Look over there! The cave entrance is blocked by a landslide.'),
        ('아, 안타깝군. 보물들이 안에 있을수도 있는데말야.... 이제 더이상 알수 없겠지.', 'Ah, that\'s a shame. There might have been treasures inside.... We\'ll never know now.'),
        ('보우이, 이제 배로 돌아가자.', 'Bowie, let\'s go back to the ship.'),
        ('보우이, 저길봐! 배를 모두 부쉈어.', 'Bowie, look! They\'ve taken the ship completely apart.'),
        ('와, 저것이 우리의 새로운 마을이군! 하지만 예전 그란실이 훨씬 멋졌었지. 기운내라고!', 'Wow, so that is our new town! But the old Granseal was much cooler. Cheer up!'),
        ('그들은 새로운 마을을 짓기위해 열심히 일했다. 일년이 지났다.', 'They worked hard to build the new town. One year passed.'),
        ('[그란실성]', '[Granseal Castle]'),
        ('쿨럭...보시다시피 우리의 새로운 마을은 다시 지어지고 있소. 하지만 더 이상 사고가 없다면 다행이오. 여러분들은 마을을 지키기엔 아직 너무 어리오.', 'Cough... as you can see, our new town is being rebuilt. It would be fortunate if there are no more accidents. You are still too young to protect the town.'),
        ('허나 여러분들은 그란실의 병사들이오! 새로운 마을을 개선시키도록 최선을 다하시오!', 'But you are soldiers of Granseal! Do your best to improve the new town!'),
        ('폐하!', 'Your Majesty!'),
        ('쿨럭...쿨럭... 폐하!', 'Cough... cough... Your Majesty!'),
        ('그란실의 모든이들이 일년동안 정말 열심히 일해주었습니다. 그들의 정성에 대해 감사를 하시는것이 마땅하다고 여깁니다.', 'Everyone in Granseal has worked very hard for a year. I believe it is only fitting that you thank them for their dedication.'),
        ('아...난 더이상 할말이 없네.', 'Ah... I have nothing more to say.'),
        ('아...아무것도요? 으으음...알겠습니다. ', 'Ah... nothing? Hmmm... I see. '),
        ('아스트랄님, 폐하 대신 말씀해주시길 바랍니다.', 'Sir Astral, please speak on behalf of His Majesty.'),
        ('으으으으음...알겠습니다.', 'Hmmmm... alright.'),
        ('우리가 여기에 정착한지 일년이 되었소. 성,마을...모든것들이 순탄하게 진행되어가고 있소. 하지만 한가지고 부족하다오. 무엇이겠소? 바로 무역이오! 우리는 다른 마을들과 동맹을 맺어야만하오.', 'It has been a year since we settled here. The castle, the town... everything is going smoothly. But one thing is lacking. What is it? Trade! We must form alliances with other towns.'),
        ('맞습니다, 맞습니다. 감사합니다, 아스트랄님!', 'You\'re right, absolutely right. Thank you, Sir Astral!'),
        ('오늘은 이만 끝이오. 이만 해산하도록 하시오.', 'That is all for today. You are dismissed.'),
        ('왼쪽에 있는 항아리에는 Cheerful Bread(회복의 식빵)이 들어있습니다.', 'The jar on the left contains Cheerful Bread.'),
        ('오른쪽에 있는 본진에 있는 독수리문양을 뒤지면 Warrior Pride (전사의 자존심)을 얻으실수가 있습니다.', 'If you search the eagle emblem in the headquarters on the right, you will find Warrior Pride.'),
        ('그란실성주변 대화', 'Dialogue around Granseal Castle'),
        ('[그란실 마을]', '[Granseal Village]'),
        ('이상한 동물? 진짜?', 'A strange animal? Really?'),
        ('응! 아주 커다란 새라고!', 'Yeah! It\'s a huge bird!'),
        ('사람들이 새주위를 감싸고 있군. 말을 걸어볼까? 좋은 기회가 될거야. 난 새를 보러 갈게! 넌 폐하께 말씀드리라고!', 'A crowd has gathered around the bird. Shall we talk to it? This could be a great chance. I\'m going to see the bird! You go tell His Majesty!'),
        ('아, 보우이로구나. 마침 잘왔어. 마을에 아주 이상한 동물이 있어. 아주 흥미진진하다고!', 'Ah, it\'s Bowie. You came at a good time. There\'s a very strange animal in town. It\'s quite exciting!'),
        ('마을사람들이 새구경하느라 정신이 팔리는 도중에 상자들을 먹읍시다. 천사의 날개,해독초,회복의 씨앗,회복의 물방울들을 얻으실수 있습니다.', 'While the townspeople are busy looking at the bird, let\'s take the items from the chests. You can get Angel Wing, Antidote, Healing Seed, and Medical Herb.'),
        ('그란실 마을주변 대화', 'Dialogue around Granseal Village'),
        ('소년1', 'Boy 1'),
        ('중학생1', 'Boy 1'),
        ('우우우...정말 크다! 만지고 싶어!', 'Ooooh... it\'s so big! I want to touch it!'),
        ('아앗!', 'Aah!'),
        ('소년 1', 'Boy 1'),
        ('소년 2', 'Boy 2'),
        ('하하! 놓쳤다. 내가 한번해보지.', 'Haha! You missed. Let me try.'),
        ('와, 굉장히 빠르다! 아, 저기 있구나!', 'Whoa, it\'s so fast! Ah, there it is!'),
        ('소년 3', 'Boy 3'),
        ('이제 내 차례야!', 'It\'s my turn now!'),
        ('하아, 정말 빠르구나!', 'Hah, it\'s really fast!'),
        ('피터', 'Peter'),
        ('그만둬! 그만해!', 'Stop it! Knock it off!'),
        ('소년들', 'Boys'),
        ('굉장한데. 말도 한다!', 'Amazing. It can even talk!'),
        ('당연하지. 이게 너희들이 손님을 맞는 태도냐?', 'Of course. Is this how you treat a guest?'),
        ('닥쳐, 새대가리!', 'Shut up, birdbrain!'),
        ('정말 무례하군! 인간들이 이렇게 몰상식한줄은 몰랐어.', 'How rude! I didn\'t know humans could be so senseless.'),
        ('뭐?', 'What?'),
        ('소년들은 새를 치려고 한다.', 'The boys try to hit the bird.'),
        ('멈추어라!', 'Stop!'),
        ('지금 무슨짓을 하려는것이냐?', 'What do you think you are doing?'),
        ('정말 죄송합니다. 저들 대신 사과하겠습니다. 그란실에 오신것을 환영합니다. 저는 장관입니다 .저희들은 여기에 최근에 정착했습니다. 저희들은 아직 여기에 대해서 잘 모릅니다.', 'I am truly sorry. I apologize on their behalf. Welcome to Granseal. I am the Minister. We have only recently settled here, and we don\'t know much about this place yet.'),
        ('하하! 맞아요. 하지만 장관님같은 사람을 만나게 되서 정말 기쁘군요!', 'Haha! You\'re right. But I\'m so glad to meet someone as kind as the Minister!'),
        ('언제든지 여기에 계시고 싶으신만큼 머무십시오. 일단 그란실국왕폐하께 소개시켜드리겠습니다. 저를 따라오시길 바랍니다.', 'Please stay as long as you like. First, I will introduce you to King Granseal. Please follow me.'),
        ('성으로 갑시다.', 'Let\'s go to the castle.'),
        ('자네가 전설의 새라는 피닉스인가?', 'Are you the legendary bird known as the Phoenix?'),
        ('아...예, 피닉스는 맞습니다. 그런데...전설이라뇨? 그건 잘 모르겠군요.', 'Ah... yes, I am a Phoenix. But... legendary? I don\'t know about that.'),
        ('피터, 자네는 전설적인새가 맞네! 내가 듣기로는 피닉스는 신을 섬긴다고 했다.', 'Peter, you are indeed a legendary bird! I have heard that the Phoenix serves a god.'),
        ('신이요? 아, 볼카논님을 말씀하시는군요! 루크가 볼카논님을 신이라고 부르죠. 볼카논님께서 우리를 지켜주시는한 누구도 파르메키아의 평화를 깰순 없을것입니다.', 'A god? Ah, you must mean Volcanon! Luke calls Volcanon a god. As long as Volcanon protects us, no one can break the peace of Parmecia.'),
        ('볼카논? 이 땅을 창조하셨다는 신을 말씀하는건가? 오오, 정말 내 인생에 있어서 가장 값진 순간이로구나!', 'Volcanon? Are you speaking of the god who created this land? Oh, this is truly the most precious moment of my life!'),
        ('제발 자네와 같이 가서 볼카논님을 만나게 해주게!', 'Please let me go with you to meet Volcanon!'),
        ('으으음...알겠습니다. 사실, 제가 여행도중에 날개를 다쳤습니다. 여기에 도움을 요청하러 온것인데입니다. 하지만 폐를 끼쳐드리기가....', 'Hmm... alright. Actually, I injured my wing during my travels, and I came here to ask for help. But I don\'t want to be a burden....'),
        ('걱정말게나. 이 젊은이들은 폐를 아주 좋아한다네.', 'Don\'t worry. These young people love being helpful.'),
        ('젊은이들', 'young people'),
        ('보우이! 왜 진작에 도착했다고 말을 하지 않았느냐? 우리의 대화를 들었느냐? 이제 우리가 떠날 시간이 왔다! 우리는 피터와 함께 볼카노산맥에 가는것이다. 아주 먼 동쪽으로 말이다!', 'Bowie! Why didn\'t you say you had arrived? Did you hear our conversation? The time has come for us to leave! We are going to the Volcano Range with Peter. It\'s far to the east!'),
        ('아스트랄님!', 'Sir Astral!'),
        ('아스트랄님께서도 같이 가신다고 하셨습니까? 안됩니다!', 'Did you say you are going too, Sir Astral? You cannot!'),
        ('왜...왜 안된다는겁니까?', 'Why... why not?'),
        ('우리는 여기에 정착한지 불과 일년이 채 지났습니다. 우리는 아직도 이 지역에 대해서 배울것이 많습니다. 아스트랄님께서 꼭 필요하십니다.', 'We have only been settled here for less than a year. We still have much to learn about this region. We need you here, Sir Astral.'),
        ('그란실', 'Minister'),
        ('장관의 말이 맞네. 자네는 여기에 남아있어야하네.', 'The Minister is right. You must remain here.'),
        ('보우이, 자네의 동료들을 데리고 피터와 함께 가게나. 아스트랄, 동의하는가?', 'Bowie, take your companions and go with Peter. Astral, do you agree?'),
        ('흐으으으음.... 예...예.', 'Hmmmm.... Yes... yes.'),
        ('그럼, 저들은 내 동료들이군요!', 'Then they are my companions!'),
        ('난 피터야. 네 호의를 고맙게 받아들이겠어. 볼카노산맥은 동쪽에 있어....여기서 아주 멀지.', 'I\'m Peter. I gratefully accept your kindness. The Volcano Range is to the east.... quite far from here.'),
        ('보우이는 피터와 같이 동행하기로 했다.', 'Bowie decided to accompany Peter.'),
        ('King Granseal\n                  ', 'King Granseal '),
        ('장관, 선물을 가지고 오게나!', 'Minister, bring the gift!'),
        ('예, 폐하.', 'Yes, Your Majesty.'),
        ('작별선물이네. 받게나.', 'It\'s a parting gift. Take it.'),
        ('보우이는 100 금화를 얻었다.', 'Bowie received 100 Gold coins.'),
        ('보우이,행운을 빈다.', 'Bowie, good luck.'),
        ('피터와의 여행에 최대한 많은 친구들을 찾아내거라.', 'Find as many friends as possible for your journey with Peter.'),
        ('그란실 성/마을주변 대화', 'Dialogue around Granseal Castle/Village'),
        ('이제 또 여행을 떠납니다. 가시기 전에 무기를 단단히 준비하시고 떠납시다. 보우이에겐 Middle Sword(미들 소드), 체스터에겐 Spear(투창),쟈하에겐 Hand Axe(손도끼)를 장착시킵시다. 동쪽으로 가시면 전투가 시작됩니다.', 'It\'s time to set out on another journey. Before you leave, make sure to properly equip your weapons. Equip Bowie with Middle Sword, Chester with Spear, and Jaha with Hand Axe. A battle will begin once you head east.'),
        ('[전투 9]', '[Battle 9]'),
        ('* 보스 : 강가의 동굴에 가까운 흡혈박쥐', '* Boss: Vampire Bat closest to the riverside cave'),
        ('피터와의 첫 전투입니다. 보시다시피 컴퓨터가 조종하기때문에 그리 큰 도움은 못됩니다. 오히려 키위같은 약체들에게 먹이려고 거의 죽여놓은 캐릭터들을 홀랑 먹어버리는 얌체이기도 하죠. 역시 키위를 보호하면서 전진하시며 오는 적들은 모두 무찌르시면 됩니다.', 'This is your first battle with Peter. As you can see, since he is computer-controlled, he isn\'t much help. In fact, he tends to steal kills on enemies you\'ve weakened for weaker characters like Kiwi. Just keep protecting Kiwi as you advance and defeat all the enemies that approach.'),
        ('곧 가면 마을이 있습니다. 거기로 들어갑시다.', 'There is a town nearby. Let\'s go inside.'),
        ('[리블 마을]', '[Ribble Village]'),
        ('흐으음?', 'Hmm?'),
        ('너희들은 새 마을에서 왔구나, 그렇지?', 'You guys are from the new town, aren\'t you?'),
        ('또왔군! 촌장님! 촌장님!', 'They\'re here again! Elder! Elder!'),
        ('촌장의 집으로 들어갑니다. 다른집들은 모두 잠겼습니다.', 'Enter the Elder\'s house. All the other houses are locked.'),
        ('촌장', 'Elder'),
        ('너희들은 누구냐? 도대체 뭐냐?', 'Who are you? What do you want?'),
        ('병사들이 방금 왔다 갔어요. 분명 대문밖에서 기다리고 있을겁니다. 조심하세요!', 'The soldiers just left. They must be waiting outside the gate. Be careful!'),
        ('정말 끈질기구나. 무얼 원하는거냐?! 갑자기 파르메키아에 나타나서는 성을 지어? 너희들이 누구인지는 모르지만 모든 큰도시들은 전쟁을 좋아하지! 나는 정말 너희들같은 무례하고 폭력적인 방문자들은 정말 처음 보는구나!', 'You are persistent. What do you want?! Suddenly appearing in Parmecia and building a castle? I don\'t know who you are, but all big cities love war! I have never seen such rude and violent visitors like you!'),
        ('맞아! 너희들은 파르메키아를 정복하려고 온것이야!', 'That\'s right! You came to conquer Parmecia!'),
        ('우리들은 절대 너희들을 따르지 않겠다! 꺼져라!', 'We will never follow you! Get out!'),
        ('정말 말이 많군!', 'He talks too much!'),
        ('야, 보우이! 뭐라고 말좀 해봐. 정말 못참겠군!', 'Hey, Bowie! Say something. I can\'t stand this anymore!'),
        ('이보세요! 할아버지의 감정은 이해해요, 하지만 제말을 들어보세요.', 'Listen! I understand how you feel, but please listen to what I have to say.'),
        ('뭣때문에?', 'About what?'),
        ('저는 그란실에서 오지 않았습니다. 저는 단지 그곳을 방문하였을뿐이지요.... 그란실사람들이 파르메키아로 정복하러온것 같나요? 틀렸어요. 그란실사람들은 자신들의 고향을 재해때문에 버리고 여기로 피난올수밖에 없었다구요. 실제로는 좋은 사람들이에요! 그렇게 짜증내실 필요는 없잖아요!', 'I am not from Granseal. I was just visiting.... Do you think Granseal people came to conquer Parmecia? You\'re wrong. The people of Granseal were forced to flee their home because of a disaster. They are actually good people! There\'s no need to be so irritable!'),
        ('그러는 너는 누구냐?', 'And who are you?'),
        ('저는 피터입니다! 저는 볼카노산맥에 사는 피닉스이죠!', 'I\'m Peter! I\'m a Phoenix from the Volcano Range!'),
        ('피닉스! 전설의새라는?', 'A Phoenix! The legendary bird?'),
        ('저희가 전설적인건 잘 모르겠습니다만....', 'I don\'t know about us being legendary....'),
        ('정말 만나서 반갑네! 오, 그럼 저들은 자네 친구들이구만. 맙소사!', 'It\'s a pleasure to meet you! Oh, so they are your friends. My goodness!'),
        ('물론 이제부터 리블은 그란실의 동맹국이 되겠습니다. 다음에 방문하신다면 따스히 맞아주기로 약속하지요!', 'Of course, from now on, Ribble will be an ally of Granseal. We promise to welcome you warmly the next time you visit!'),
        ('마을입구로 가시면 어느 켄타우르스가 돌아다니는것을 보입니다. 대화를 하면 매이라는 궁수를 동료로 맞이하실수 있습니다.', 'Near the town entrance, you\'ll see a centaur wandering around. If you talk to her, you can recruitment May the archer.'),
        ('매이', 'May'),
        ('이 마을에 있는 사람들은 죄다 겁쟁이들이야. 언제 모험을 떠날것이지? 정말 참을수가 없어! 아, 나도 같이 가도 괸찮겠지?', 'Everyone in this town is a coward. When are we going on an adventure? I can\'t stand it! Oh, would it be okay if I come along too?'),
        ('래인저 매이가 동료가 되었다.', 'May the Ranger joined the force.'),
        ('자, 출발하자고!', 'Alright, let\'s set out!'),
        ('놀이터의 정가운데에는 미스릴이 있습니다.', 'There is Mithril in the center of the playground.'),
        ('남서쪽의 항아리안에는 지력의 꿀이 있습니다.', 'There is Brain Candy in the jar in the southwest.'),
        ('리블마을주변/남쪽신전 대화', 'Dialogue around Ribble Village/South Shrine'),
        ('Slade를 위해 Dagger(단검)을 사줍시다.', 'Let\'s buy a Dagger for Slade.'),
        ('계속 동쪽으로 향하시면 다음 전투가 시작됩니다.', 'Continue heading east and the next battle will begin.'),
        ('[전투 10]', '[Battle 10]'),
        ('* 보스 : 강가의 가까운 다크 드워프', '* Boss: Dark Dwarf closest to the river'),
        ('지난번 전투와 비슷합니다. 이번 전투에는 마녀가 Power Ring(힘의반지)를 가지고 있는데 얻으시면 장착시 공격력이 5가 올라갑니다. 반지를 계속 얻을수 있는 방법이 있긴합니다. 적을 조종하는 비기를 게임초기에 선택하고 게임을 로딩한후 전투에서 마녀의 차례가 오면 반지를 버립니다. 그후 보우이의 차례가 오면 Egress(귀환)마법을 써서 다시 돌아옵니다. 그럼 상점에 가서 Deal섹션을 보면 반지가 있습니다. 이런식으로 계속해서 모두에게 반지한가락지씩은 맞춰줄수 있습니다.', 'This is similar to the previous battle. In this battle, a Witch carries a Power Ring; if you get it, equipping it increases attack power by 5. There is a way to get multiple rings: use the control-enemy cheat selected at the start of the game, wait for the Witch\'s turn to drop the ring, then use Egress on Bowie\'s turn. The ring will then appear in the shop\'s Deals section. You can repeat this to equip everyone with a ring.'),
        ('계속 동쪽으로 가하시면 다리가 있습니다. 다리를 지나신후 쑥 들어간 산쪽을 뒤지시면 미스릴을 찾으실수 있습니다.', 'Continue heading east and you will find a bridge. After crossing the bridge, search the recessed area of the mountain to find Mithril.'),
        ('미스릴을 잡수신후 위에 있는 동굴에 들어갑시다.', 'After getting the Mithril, enter the cave above.'),
        ('이 어두운 동굴을 지나면 볼카노산맥의 길목에 다다르게 될거야.', 'If we pass through this dark cave, we\'ll reach the path to the Volcano Range.'),
        ('하지만 이 동굴이 홉고블린의 집이라고도 들었지.', 'But I\'ve also heard that this cave is home to Hobgoblins.'),
        ('맞아!', 'Correct!'),
        ('누...누가 말한거지?', 'Wh... who said that?'),
        ('나! 홉고블린!', 'Me! A Hobgoblin!'),
        ('홉고블린', 'Hobgoblin'),
        ('내 집에 온것을 환영한다. 여기서 절대 못나갈테니 마음껏 즐기라고!', 'Welcome to my home. You\'ll never leave, so make yourselves comfortable!'),
        ('[전투 11]', '[Battle 11]'),
        ('* 보스 : 홉고블린', '* Boss: Hobgoblin'),
        ('어두운곳에서의 전투입니다. 지도를 보시면 약간 도움이 되실것입니다. 지형이 불리하기 때문에 다른 병사들이 따라잡을수 있도록 천천히 진행합시다.', 'This is a battle in the dark. Looking at the map might help. Since the terrain is unfavorable, proceed slowly so your other soldiers can keep up.'),
        ('동굴의 보물상자안에는 Silver Tank(실버탱크)라는 전직 아이템이 있습니다.', 'Inside the chest in the cave is a promotion item called Silver Tank.'),
        ('동굴 밖을 나가신후 서쪽으로 가시면 폴카마을로 들어가게 됩니다.', 'After leaving the cave, head west to enter Polca Village.'),
        ('[폴카 마을]', '[Polca Village]'),
        ('땅밑으로 만들어진 집안의 항아리에는 보호의 우유가 있습니다.', 'There is Protect Milk in a jar inside one of the underground houses.'),
        ('다음 전투를 대비해서 무기도 삽시다. 보우이를 위한 Long Sword(롱소드)와 카진,사리를 위한 Bronze Rod(브란즈 로드)를 사서 장착합니다.', 'Let\'s buy weapons for the next battle. Buy and equip a Long Sword for Bowie and Bronze Rods for Kazin and Sarah.'),
        ('폴카 마을주변 대화', 'Dialogue around Polca Village'),
        ('마을을 북서쪽으로 떠나시면 땅이 흔들리면서 소년하나가 나타납니다.', 'As you leave the village to the northwest, the ground shakes and a boy appears.'),
        ('수인', 'Beastman'),
        ('수인은 소년을 조사해본다.', 'The Beastman examines the boy.'),
        ('맙소사! 정말 크게 다쳤구나!', 'My goodness! He\'s seriously injured!'),
        ('촌장님, 촌장님!', 'Elder! Elder!'),
        ('왜 이렇게 소란이냐?', 'What is all the noise about?'),
        ('촌장님, 산에서 내려온 소년하나가 아주 큰 부상을 당했습니다!', 'Elder, a boy who came down from the mountain is badly hurt!'),
        ('뭐라고?!', 'What?!'),
        ('아아아...이 소년이 눈을 아주 크게 다쳤구나! 분명 산사태에 붙잡혔을테지....', 'Oh no... this boy\'s eyes are seriously injured! He must have been caught in a landslide....'),
        ('당장 응급조치를 해야합니다!', 'We must give him first aid immediately!'),
        ('맞네! 집안으로 업고오게나!', 'You\'re right! Carry him into the house!'),
        ('계속 진행하시면 다음 전투가 시작됩니다.', 'Continue on and the next battle will begin.'),
        ('저들은 누구지?', 'Who are they?'),
        ('무언가를 찾고있는것 같아.', 'It looks like they\'re searching for something.'),
        ('다크스모크 ', 'Dark Smoke '),
        ('여기에도 없어...낭떠러지 밑에도 없어....', 'He\'s not here either... not even at the bottom of the cliff....'),
        ('홉고블린 ', 'Hobgoblin '),
        ('여기저기에 전투의 흔적이 있다! 그렇다면 베도의 조인들과?', 'There are signs of battle everywhere! Could it be the Birdmen of Bedoe?'),
        ('데스아처', 'Death Archer'),
        ('그럴수도...여기 용암석들이 보이나?', 'Perhaps... do you see these lava stones?'),
        ('볼카논말고는 할수있는자가 없지. 그분께서는 생전 조인을 죽이신적이 없으신데...', 'No one but Volcanon could have done this. But he has never killed a Birdman before...'),
        ('거기 누구지?', 'Who\'s there?'),
        ('다크스모크 ', 'Dark Smoke '),
        ('멍청한 폴카꼬마놈들같으니라고!', 'Stupid brats from Polca!'),
        ('데스아처 ', 'Death Archer '),
        ('폴카놈들은 평화에 사는 겁쟁이놈들이다. 저놈들은 절대 살아서 못돌아간다!', 'The people of Polca are cowards living in peace. They will never return alive!'),
        ('[전투 12]', '[Battle 12]'),
        ('* 보스 : 데스 아처', '* Boss: Death Archer'),
        ('볼카논이 파놓은 용암구멍에 있으시면 방어보너스가 있으니 그점을 이용합시다. 도중에 길이 두갈래로 갈라지는데 몇명정도는 보내서 그쪽에 있는 적들을 쓸어버립시다. 나중에 데스아처와 싸울때 도와주러 올수도 있으며 중간에 마법을 이용해 한칸 벌어진곳을 넘어 공격하는 경우도 있습니다.', 'Use the lava pits created by Volcanon for a defense bonus. The path splits in two; send a few people to clear the enemies on that side. They can help when fighting the Death Archer later, or use magic to attack across the gaps.'),
        ('어떻게...악마들을...무찌를수가 있는거지?', 'How... how could they defeat... demons?'),
        ('아! 목주위에 악의 보석을 두르고 있구나. 너였어 보우이. 너를 기다리고 있었다.', 'Ah! You\'re wearing the Jewel of Evil around your neck. It was you, Bowie. I\'ve been waiting for you.'),
        ('보우이, 들었어? 기다리고 있었대. 왜 악마들이 너를 원하는걸까?', 'Bowie, did you hear that? He said he was waiting for you. Why do the demons want you?'),
        ('[베도]', '[Bedoe]'),
        ('경비병 1', 'Guard 1'),
        ('누구야?', 'Who\'s there?'),
        ('경비병 2', 'Guard 2'),
        ('베도는 조인들만 출입이 가능하다!', 'Only Birdmen are allowed to enter Bedoe!'),
        ('너무 힘주지 말라고!', 'Don\'t be so tense!'),
        ('아...', 'Ah...'),
        ('피터님이시군요! 죄송합니다, 피터님! 잘 오셨습니다. 볼카논님께서 기다리십니다!', 'It\'s Master Peter! Our apologies, Master Peter! Welcome back. Volcanon is waiting for you!'),
        ('이상하군...', 'Strange...'),
        ('방금 기억이 났는데... 왜 여기서 경비를 하는것이지?', 'I just remembered... why are you standing guard here?'),
        ('무슨일이 일어났나?', 'Did something happen?'),
        ('경비병', 'Guard'),
        ('예, 최근에 악마들이 쳐들어왔어요.', 'Yes, some demons attacked recently.'),
        ('악마들이?', 'Demons?'),
        ('예, 악마군이요. 악마군대장들이 볼카논님의 성스러운 보호막을 뚦었지요. 하지만 걱정마세요. 볼카논님께서 모든 악마들을 물리치셨으니까요.', 'Yes, the demon army. Their leaders broke through Volcanon\'s sacred barrier. But don\'t worry, Volcanon defeated them all.'),
        ('방금 우리와 싸웠던 악마들은 잔병들일거야 그럼!', 'Then the demons we just fought must have been stragglers!'),
        ('다른 악마들도 만났다고요?', 'You met other demons too?'),
        ('그만, 멈춰! 이미 모두 무찔렀어.', 'Cut it out! We\'ve already defeated them all.'),
        ('그거 다행이군요! 하지만...', 'That\'s good to hear! However...'),
        ('다시 가서 재확인을...', 'We should go back and double-check...'),
        ('만일을 대비해서요.', 'Just in case.'),
        ('저희는 폴카마을로 순찰을 하러 가겠습니다. 피터님, 베도폐하를 먼저 만나보시길 바랍니다.', 'We\'ll go on a patrol to Polca Village. Master Peter, please see the King of Bedoe first.'),
        ('보우이, 가자. 내가 베도폐하께 소개시켜줄게.', 'Bowie, let\'s go. I\'ll introduce you to the King of Bedoe.'),
        ('3층의 항아리에는 Quick Ring(민첩의 반지가 있습니다.', 'There is a Quick Ring in the jar on the third floor.'),
        ('베도에도 무기상점이 있습니다. 체스터에겐 Steel Lance(스틸 랜스)를, 쟈하에게는 Middle Axe(중도끼)를, 슬래이드에게는 Knife(나이프)를, 매이에게는 Iron Arrow(아이언 애로우)를 사줍시다. 계속 올라가시면 결국 베도왕에게 가게 됩니다.', 'There is also a weapon shop in Bedoe. Buy a Steel Lance for Chester, a Middle Axe for Jaha, a Knife for Slade, and an Iron Arrow for May. Continue upward and you will eventually reach the King of Bedoe.'),
        ('베도 주변 대화', 'Dialogue around Bedoe'),
        ('조인 ', 'Birdman '),
        ('예, 악마군대장은 아주 강했습니다. 하지만 볼카논신께서 모든 악마들을 쓸어버리셨습니다.', 'Yes, the demon leader was very strong. But Volcanon wiped out all the demons.'),
        ('베도왕 ', 'King Bedoe '),
        ('악마군대장은 어찌하고?', 'What happened to the demon leader?'),
        ('달아났습니다.', 'He fled.'),
        ('어떻게든 쫒아갈수가 없나? 힘을 되찾기전에 잡아야만하네.', 'Is there any way to catch him? We must capture him before he regains his strength.'),
        ('그들은 그란스섬에서 왔나요?', 'Did they come from Grans Island?'),
        ('내 생각엔 그렇다. 아마 죽었을테지. 하지만 다음 공격이 있을수도 있다. 조심하거라!', 'I believe so. He may be dead, but there could be another attack. Be careful!'),
        ('루크', 'Luke'),
        ('피터, 피터!', 'Peter, Peter!'),
        ('루크, 잘 지냈니? 폐하, 건강히 보이시는군요.', 'Luke, how have you been? Your Majesty, you look well.'),
        ('내 친구, 피터여. 여행은 어땠나?', 'My friend Peter, how was your journey?'),
        ('제 친구를 소개시켜드리겠습니다.', 'I\'d like to introduce my friend.'),
        ('이쪽은 보우이입니다. 그란스에서 왔고요...', 'This is Bowie. He\'s from Grans...'),
        ('알아. 그란실의 아스트랄님의 제자이지.', 'I know. He\'s Sir Astral\'s apprentice from Granseal.'),
        ('그걸 어떻게 알지?', 'How do you know that?'),
        ('아스트랄님께서 말씀해주셨으니까.', 'Because Sir Astral told me.'),
        ('뭐?! 그란실에 가기라도 했단말야? ', 'What?! You actually went to Granseal? '),
        ('볼카논님의 사신으로 말이지.', 'As a messenger for Volcanon.'),
        ('게다가 내가 듣기로는 누군가가 제온의 봉인을 풀었다고 한다. 그란스사람들은 아주 엄청난 일을 저지르고 만거야. 제온은 세계를 파괴할지도 모른다...', 'Furthermore, I\'ve heard that someone has broken the seal on Zeon. The people of Grans have done something terrible. Zeon may destroy the world...'),
        ('말을 끊어서 죄송합니다만, 그렇게 쎈가요?', 'I\'m sorry to interrupt, but is he really that strong?'),
        ('볼카논', 'Volcanon'),
        ('제온은 모든 악마들의 왕이다.', 'Zeon is the King of all devils.'),
        ('조인', 'Birdman'),
        ('피터, 볼카논님을 만나뵈는게 좋을거야. 아마도 피터 너를 보면 볼카논님도 좀 진정하시겠지.', 'Peter, you should go see Volcanon. I think he might calm down once he sees you.'),
        ('아, 화나계신거야? 그럼 다음에...', 'Ah, is he angry? Then maybe next time...'),
        ('다음이라니 무슨. 여태까지 널 기다리고 계셨어.', 'What do you mean "next time"? He\'s been waiting for you all this time.'),
        ('그래? 알았어, 갈게. 보우이, 따라와.', 'Oh? Alright, I\'ll go. Bowie, follow me.'),
        ('피터, 보우이와 같이 가는것이냐?', 'Peter, are you going with Bowie?'),
        ('물론이지요. 왜요?', 'Of course. Why?'),
        ('그분께서 생각하시길 그란실사람들은...', 'He thinks that the people of Granseal...'),
        ('베도폐하, 아무래도 보우이가 볼카논님을 만나는게 좋하다고 생각합니다. 볼카논님과 대화를 해야한다고 생각합니다.', 'Your Majesty, I believe it would be best for Bowie to meet Volcanon. He needs to speak with him.'),
        ('흐으음...그말도 일리가 있다. 피터, 가도 좋다.', 'Hmm... that makes sense. Peter, you may go.'),
        ('예. 아무튼 가자.', 'Yes. Anyway, let\'s go.'),
        ('끝까지 올라가시면 드디어 볼카논신을 만나게 됩니다.', 'If you go all the way up, you will finally meet the god Volcanon.'),
        ('볼카논 신전대화', 'Dialogue at Volcanon Temple'),
        ('볼카논님! 돌아왔습니다!', 'Volcanon! I have returned!'),
        ('다시 왔구나, 피터. 건강히 보이는구나.', 'You have returned, Peter. You look well.'),
        ('예! 여행은 무척 흥미로웠습니다.', 'Yes! My travels were very interesting.'),
        ('좋은소식이로구나.', 'That is good to hear.'),
        ('그래, 무엇이 흥미로웠지?', 'So, what did you find interesting?'),
        ('땅에 사는 많은 사람들을 만났습니다.', 'I met many people living on the ground.'),
        ('모두들 서로를 돕고 삽니다. 저 역시 몇몇 친구를 만났구요.', 'They all live helping each other. I\'ve met some friends too.'),
        ('참 훌륭하구나. 정말 좋은 경험이었겠구나.', 'That\'s wonderful. It must have been a great experience.'),
        ('친구한명을 데려왔습니다.', 'I\'ve brought a friend with me.'),
        ('이쪽은 보우이입니다. 그란실에서 왔습니다.', 'This is Bowie. He\'s from Granseal.'),
        ('그란실!', 'Granseal!'),
        ('그란스섬의 사람들은 아주 심각하고 엄청난 문제를 세상에 불러일으켰다!', 'The people of Grans Island have brought a serious and terrible problem to the world!'),
        ('볼카논님?', 'Master Volcanon?'),
        ('그들은 전설의 악마인 제온을 깨웠어!', 'They have awakened the legendary devil, Zeon!'),
        ('나는 여지껏 이땅에 있는 모든 사람들을 보호해주었다.', 'I have protected everyone on this land until now.'),
        ('나는 그들을 용서할수가 없어!', 'I cannot forgive them!'),
        ('볼카논님, 제발 진정하세요!', 'Master Volcanon, please calm down!'),
        ('보우이가 저지른게 아니잖아요!', 'It wasn\'t Bowie\'s fault!'),
        ('이 땅에 있는 모든이들에게 책임이 있다.', 'Everyone on this land bears responsibility.'),
        ('그들은 이 문제를 그들 자신이서 해결해야할것이야.', 'They must solve this problem themselves.'),
        ('보우이는 이제 어떻게 해야하나요?', 'What should Bowie do now?'),
        ('내 보호는 지금부터 파기되었다!', 'My protection is withdrawn from this moment!'),
        ('보우이는 악마들을 스스로 맞서야할것이야.', 'Bowie must face the demons on his own.'),
        ('하지만...', 'But...'),
        ('악마군대장들도 볼카논님과 맞먹을 정도로 강했잖아요!', 'Even the demon leaders were strong enough to rival you, Master Volcanon!'),
        ('만약 모든 인간들이 파멸된다면 그것도 괸찮다. 그것이 그들의 운명일테니.', 'If all humans are destroyed, so be it. That would be their destiny.'),
        ('나는 그들이 용기를 보여주기를 바란다.', 'I hope they show courage.'),
        ('그들은 그 악마를 다시 봉인해야할것이야.', 'They must seal that devil away again.'),
        ('그럼, 보우이에게 조언이라도 주시길 바랍니다.', 'Then, please at least give Bowie some advice.'),
        ('보우이, 네 보석들의 힘을 믿거라.', 'Bowie, trust in the power of your jewels.'),
        ('그 보석들은 빛과 어둠에서 온것이다.', 'Those jewels came from light and darkness.'),
        ('빛과 어둠이 하나가 되면 진정한 힘을 발휘할수 있을것이다.', 'When light and darkness become one, true power can be unleashed.'),
        ('이제 가도 좋다. 제온이 패배하기전엔 누구도 보고싶지 않다.', 'You may go now. I do not wish to see anyone until Zeon is defeated.'),
        ('볼카논님!', 'Master Volcanon!'),
        ('보우이, 그 악마를 우리들끼리 무찌르자!', 'Bowie, let\'s defeat that devil ourselves!'),
        ('볼카논님께서 저렇게 차가운 마음을 가지신 분이신줄 몰랐어.', 'I didn\'t know Master Volcanon could be so cold-hearted.'),
        ('알았어, 내가 도와주지! 너와 같이 가서 제온을 다시 봉인하겠어!', 'Alright, I\'ll help you! I\'ll go with you and seal Zeon away again!'),
        ('피닉스 피터가 동료가 되었다.', 'Peter the Phoenix joined the force.'),
        ('볼카논신께서 아주 화나셨지? 이제 더이상 그분에게 기댈수는 없어. 우리 스스로 해야만해!', 'Master Volcanon is very angry, isn\'t he? We can no longer depend on him. We must do it ourselves!'),
        ('우리는 볼카논님을 진정시킬수 없다. 볼카논님의 보호가 없이는 이땅의 사람들은 사라질것이다. 오직 트리스탄과 베도만 살아남을테지.', 'We cannot calm Volcanon down. Without his protection, the people of this land will perish. Only Tristan and Bedoe will survive.'),
        ('볼카논신께서 이땅의 사람들을 저버리셨다. 그분께서 명령하신대로 제온을 죽일텐가?', 'The god Volcanon has abandoned the people of this land. Will you kill Zeon as he commanded?'),
        ('아니오', 'No'),
        ('그렇다면 베도에서 살아도 좋다. 적어도 여기는 안전할테니.', 'Then you may live in Bedoe. At least it\'s safe here.'),
        ('예', 'Yes'),
        ('정말 명예로운 사나이로구나! 그렇다면 크리드를 보러가거라. 과거 악마군대장이었다. 아마 분명 무슨 정보를 줄수 있을것이다. 강가를 지나야 크리드의 저택으로 갈수 있다. 아마 폴카가 뗏목을 가지고 있을테지.', 'You are a truly honorable man! Then go see Creed. He was once a demon leader. He might be able to give you some information. You must cross the river to reach Creed\'s mansion. Polca should have a raft.'),
        ('촌장에게 뗏목을 준비하라고 하여라.', 'Tell the Elder to prepare the raft.'),
        ('옛, 폐하!', 'Yes, Your Majesty!'),
        ('피터, 보우이를 도와주길 바란다. 보우이, 행운을 비네!', 'Peter, please help Bowie. Bowie, good luck!'),
        ('베도성 주변 대화', 'Dialogue around Bedoe Castle'),
        ('베도 입구에서 왼쪽의 나무들틈에 들어가시면 이벤트가 발생합니다.', 'If you enter the gap between the trees on the left at the entrance of Bedoe, an event will occur.'),
        ('나중에 동료를 얻는 이벤트로 다음 전투를 끝내시면 다시는 발생하지 않으므로 지금 하셔야합니다.', 'This is an event to gain a companion later. Since it won\'t happen again after the next battle, you must do it now.'),
        ('아기새', 'Baby Bird'),
        ('어미새', 'Mother Bird'),
        ('앗, 스크리치!', 'Ah, Screech!'),
        ('고맙습니다! 정말 고맙습니다! 스크리치는 무사하군요.', 'Thank you! Thank you so much! Screech is safe.'),
        ('베도병사들은 모두 겁쟁이야!', 'The soldiers of Bedoe are all cowards!'),
        ('닥쳐!', 'Shut up!'),
        ('내 동료들이!', 'My companions!'),
        ('드워프', 'Dwarf'),
        ('넌 우리의 포로야. 널 죽이게끔 만들지말라.', 'You are our prisoner. Don\'t make me kill you.'),
        ('더 이상의 장난은 없다. 너흰 우리들을 저지할 힘이 없어! 자, 이제 그 부상당한 꼬마를 내놓아라!', 'No more games. You don\'t have the power to stop us! Now, hand over that injured brat!'),
        ('게르할트', 'Gerhalt'),
        ('저자의 말을 듣지 마시오!', 'Don\'t listen to him!'),
        ('여러분들과 같이 악마들과 싸워 오들러를 보호하겠습니다!', 'I will fight the demons alongside the rest of you to protect Oddeye!'),
        ('네놈들!', 'You bastards!'),
        ('아, 보우이, 피터!', 'Ah, Bowie, Peter!'),
        ('루크! 네가 왜 여기 있는거야?', 'Luke! Why are you here?'),
        ('너희들을 위해 뗏목을 얻으러 왔어. 폴카마을사람들은 이 악마들에게 조종당하고 있어. 나를 속였다고!', 'I came to get a raft for you. The people of Polca Village are being controlled by these demons. They tricked me!'),
        ('루크왕자님, 정말 죄송하게됐습니다.', 'Prince Luke, I am truly sorry.'),
        ('폴카마을사람들은 싸우지 않을것입니다. 대신 제가 같이 싸도록 해주십시오!', 'The people of Polca Village will not fight. Instead, let me fight with you!'),
        ('늑대인간 게르할트가 동료가 되었다.', 'Gerhalt the Wolfman joined the force.'),
        ('좋았어!', 'Great!'),
        ('나도 잊지 말라구!', 'Don\'t forget about me!'),
        ('아직도 우리에게 저항하겠다는건가?! 그 댓가로 너희들은 모두 죽는다!!', 'You still intend to resist us?! In return, you shall all die!!'),
        ('[전투 13]', '[Battle 13]'),
        ('* 보스 : 매스터 법사', '* Boss: Master Monk'),
        ('피터와 게르할트라는 강력한 원군이 있음에도 불구하고 이 전투는 꽤 난이도가 높습니다. 일단 북쪽의 적들을 모두 소탕합시다. 그런다음 시계방향으로 돌아서 진행하는쪽을 추천합니다. 계단쪽으로 내려오시면 떼거지로 달려와서 길을 막습니다.', 'Despite having powerful allies like Peter and Gerhalt, this battle is quite difficult. First, clear out all the enemies to the north. Then, it\'s recommended to proceed clockwise. If you come down the stairs, they will swarm you and block the path.'),
        ('루크, 괜찮아? 루크!', 'Luke, are you okay? Luke!'),
        ('까악! 날 기절시켰군.', 'Caw! You knocked me out.'),
        ('악마들은 어디있지? 보우이, 네가 물리쳤나? 베도에는 아무도 그렇게 싸울수 있는 사람이 없어. 정말 고맙다.', 'Where are the demons? Bowie, did you defeat them? There is no one in Bedoe who can fight like that. Thank you so much.'),
        ('보우이는 대단한 전사야. 볼카논님은 보우이가 얼마나 잘싸우는지 모른다고!', 'Bowie is a great warrior. Volcanon has no idea how well Bowie fights!'),
        ('곧 아실테지. 이제 촌장을 만나서 뗏목을 얻자고!', 'He\'ll find out soon enough. Now, let\'s see the Elder and get a raft!'),
        ('보우이는 조인 루크를 데려가기로 하였다.', 'Bowie decided to take Luke the Birdman with him.'),
        ('촌장에게 이야기를 해야합니다. 한번해서는 안됩니다. 두번,세번,이벤트가 진행될때까지 이야기를 겁시다.', 'You must talk to the Elder. Not just once. Talk to him twice, three times, until the event proceeds.'),
        ('제...제발...저 소년을 데려가시오!', 'Pl... please... take that boy away!'),
        ('제제제제제발...죽이지 마시오!', 'Pl... pl... please... don\'t kill me!'),
        ('제발 데려가시오!', 'Please take him away!'),
        ('히이이이익!', 'Hieeeeeek!'),
        ('잘못했습니다! 정말 잘못했습니다! 빙의만은 하지 말아주시오!', 'I was wrong! I was truly wrong! Just please don\'t possess me!'),
        ('무슨소리를 하는거야?', 'What are you talking about?'),
        ('몰라...정말 맛이 갔군!', 'I don\'t know... he\'s really lost it!'),
        ('이봐요, 촌장님. 저희는 살아있다고요!', 'Hey, Elder. We\'re alive!'),
        ('촌장은 루크를 조심스럽게 조사한다.', 'The Elder carefully examines Luke.'),
        ('몸이 따뜻하군! 살아있어!', 'His body is warm! He\'s alive!'),
        ('정말 모든게 후회스럽다네. 갑자기 악마들이 나타났다네. 우리들은 그들에게 대항할 힘이 없었지. 그들은 오들러만 내놓으면 아무짓도 안하겠다고 약속했지.', 'I truly regret everything. Suddenly, demons appeared. We didn\'t have the strength to resist them. They promised they wouldn\'t do anything if we just handed over Oddeye.'),
        ('그래서 오들러 대신 "저"를 보내셨다는건가요?!', 'So you sent "me" instead of Oddeye?!'),
        ('미안하네, 제발 베도폐하껜 말씀드리지 말게나!', 'I\'m sorry, please don\'t tell His Majesty!'),
        ('알았어요... 보우이에게 뗏목만 마련해주신다면요.', 'Fine... if you just provide a raft for Bowie.'),
        ('고맙네! 뗏목이라고? 알았네.', 'Thank you! A raft? Understood.'),
        ('야, 립스터!', 'Hey, Lipster!'),
        ('립스터(수인)', 'Lipster (Beastman)'),
        ('루크왕자님께 뗏목을 준비하게.', 'Prepare the raft for Prince Luke.'),
        ('하지만, 그게 우리가 가지고 있는 마지막...', 'But, that\'s the last one we have...'),
        ('그게 무슨 상관인가?! 필요하면 또 하나만들면 되지않나?!', 'What does that matter?! If it\'s necessary, we\'ll just make another one!'),
        ('예...예, 촌장님!', 'Yes... yes, Elder!'),
        ('뗏목이 곧 강에 준비될것이네. 가서 한번 살펴보지 그러나?', 'The raft will be ready in the river shortly. Why don\'t you go and take a look?'),
        ('우리를 떼놓고 싶은건가보군.', 'He seems to want us gone.'),
        ('맞아. 어쨋든 이제 뗏목이 있으니까!', 'Right. Anyway, now we have a raft!'),
        ('가자!', 'Let\'s go!'),
        ('잠시만 기다려주게나.', 'Wait, just a moment.'),
        ('만약에 가능하다면...', 'If it\'s possible...'),
        ('이 아이를 같이 데려가주게나.', 'Please take this child with you.'),
        ('이 게으른 인간같으니라고! 그 소년을 더이상 보호하기 싫다는건가?!', 'You lazy human! You mean you don\'t want to protect that boy anymore?!'),
        ('난...단지....', 'I... just....'),
        ('보우이, 저 소년을 같이 데려갈거야?', 'Bowie, are you going to take that boy with us?'),
        ('정말? 보우이, 넌 너무 착해서 탈이야.', 'Really? Bowie, you\'re too kind for your own good.'),
        ('고맙네! 오들러, 보우이가 이제 너를 보살펴줄거야. 믿어도 좋아!', 'Thank you! Oddler, Bowie will take care of you now. You can trust him!'),
        ('동감이야. 저 소년은 눈이 멀었기 때문에 우리와의 여행이 너무 힘들거야. 촌장님, 데려갈수가 없습니다, 죄송합니다.', 'I agree. Since that boy is blind, traveling with us will be too difficult for him. Elder, we cannot take him, I\'m sorry.'),
        ('하...하지만....', 'B... but....'),
        ('데려가달라고 두번다시 물어봐야하나?', 'Do I have to ask you to take him again?'),
        ('[마을을 떠날때...]', '[Upon leaving the village...]'),
        ('오들러', 'Oddler'),
        ('잠깐, 잠시만요!', 'Wait, just a second!'),
        ('제발 저도 같이 가게 해주십시오!', 'Please, let me go with you!'),
        ('정말 고맙습니다.', 'Thank you so much.'),
        ('조심해! 조심하라구.', 'Be careful! Watch out.'),
        ('예, 조심하겠습니다....', 'Yes, I\'ll be careful....'),
        ('예?', 'Pardon?'),
        ('제가 여기에 있는한 악마들은 다시 돌아올것입니다. 분명 보우이님께서는 그들을 감당해낼만한 힘을 가지고 계시겠지요?', 'As long as I stay here, the demons will return. Surely you have the strength to handle them, Master Bowie?'),
        ('하지만, 여행도중에 네가 부상당할수도 있다고!', 'But you could be injured during the journey!'),
        ('음, 내가 생각하기엔 같이 와야한다고 생각해. 만약 여기에 두고간다면 죽임을 당할지도 몰라. 너무 위험하잖아, 안그래, 보우이?', 'Hmm, I think he should come with us. If we leave him here, he might be killed. It\'s too dangerous, right, Bowie?'),
        ('분명 보호자가 필요할테지. 그럼 내가 보살펴주지.', 'He certainly needs a guardian. Then I\'ll look after him.'),
        ('자, 그럼 가자.', 'Well then, let\'s go.'),
        ('(오들러를 데려가기로 결정한후)', '(After deciding to take Oddler)'),
        ('저는 오들러라고 합니다. 제가 여기에 도착했을땐 거의 초죽음이 되어있었습니다. 아니, 사실 아무것도 기억이 나질 않습니다.... 악마들이 왜 저를 쫒는지 모르겠습니다. 송구스럽지만 앞으로 많은 폐를 끼칠것같습니다.', 'My name is Oddler. When I arrived here, I was nearly dead. No, actually, I don\'t remember anything.... I don\'t know why the demons are chasing me. I\'m sorry, but I fear I will be a burden from now on.'),
        ('보우이는 오들러를 함께 데려가기로 하였다.', 'Bowie decided to take Oddler with him.'),
        ('[마을밖]', '[Outside the village]'),
        ('자, 이제 \'악마의 꼬리\'로 가서 크리드씨를 만나자!', 'Now, let\'s go to "Devil\'s Tail" and meet Mr. Creed!'),
        ('루크도 같이 갈 모양인가본데?', 'It looks like Luke is coming along too?'),
        ('맞아. 나도 보우이와 함께 싸우고 싶어. 정말 가슴이 두근두근거리는걸?!', 'That\'s right. I want to fight alongside Bowie too. My heart is really pounding with excitement!'),
        ('조인 루크가 동료가 되었다.', 'Luke the Birdman joined the force.'),
        ('네가 이렇게 모험가인지 전혀 몰랐는걸?!', 'I had no idea you were such an adventurer!'),
        ('좋아! 와! 출발하자고!', 'Alright! Wow! Let\'s set out!'),
        ('떠나시기 전에 루크에게 롱소드를 사줍시다.', 'Before leaving, let\'s buy a Long Sword for Luke.'),
        ('[다음]', '[Next]'),
    ]

    # Sort translations by length of Korean text (longest first) to avoid partial replacements
    translations.sort(key=lambda x: len(x[0]), reverse=True)

    for kor, eng in translations:
        content = content.replace(kor, eng)
        content = content.replace(kor + ' ', eng + ' ')
        if kor.endswith(' '):
            content = content.replace(kor.rstrip(), eng)

    # Use regex for more precise path replacement to avoid duplicates
    # Case 1: src="pic/filename.ext" -> src="file/pic/filename.ext"
    content = re.sub(r'src="pic/([^"]+)"', r'src="file/pic/\1"', content)
    # Case 2: src=pic/filename.ext -> src=file/pic/filename.ext
    content = re.sub(r'src=pic/([^\s>]+)', r'src=file/pic/\1', content)
    # Case 3: <img src="file/pic/pic/filename.ext"> -> <img src="file/pic/filename.ext">
    content = content.replace('file/pic/pic/', 'file/pic/')

    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(content)

    print(f"Successfully translated and saved to {output_file}")

if __name__ == "__main__":
    translate()
